class PagesController < ApplicationController
  def home
  end

  def werewolf
    @first = params[:first_name].downcase
    @last = params[:last_name].downcase
    i = @first
    j = @last
    if i == 'a'
      k = 'White'
    elsif i == 'b'
      k = 'Lone'
    elsif i == 'c'
      k = 'Ravenous'
    elsif i == 'd'
      k = 'Ancient'
    elsif i == 'e'
      k = 'Magic'
    elsif i == 'f'
      k = 'Ebony'
    elsif i == 'g'
      k = 'Dark'
    elsif i == 'h'
      k = 'Savage'
    elsif i == 'i'
      k = 'Regal'
    elsif i == 'j'
      k = 'Rogue'
    elsif i == 'k'
      k = 'Scarlet'
    elsif i == 'l'
      k = 'Fierce'
    elsif i == 'm'
      k = 'Alpha'
    elsif i == 'n'
      k = 'Beautiful'
    elsif i == 'o'
      k = 'Blood'
    elsif i == 'p'
      k = 'Moon'
    elsif i == 'q'
      k = 'Loyal'
    elsif i == 'r'
      k = 'Scarred'
    elsif i == 's'
      k = 'Grey'
    elsif i == 't'
      k = 'Mystic'
    elsif i == 'u'
      k = 'Prime'
    elsif i == 'v'
      k = 'Graceful'
    elsif i == 'w'
      k = 'Majestic'
    elsif i == 'x'
      k = 'Wild'
    elsif i == 'y'
      k = 'Vengeful'
    elsif i == 'z'
      k = 'Cruel'
    else
      k = i
    end
    @first = k
    if j == 'a'
      k = 'Hunter'
    elsif j == 'b'
      k = 'Demon'
    elsif j == 'c'
      k = 'Howler'
    elsif j == 'd'
      k = 'Rain'
    elsif j == 'e'
      k = 'Red'
    elsif j == 'f'
      k = 'Shadow'
    elsif j == 'g'
      k = 'Storm'
    elsif j == 'h'
      k = 'Beast'
    elsif j == 'i'
      k = 'Bane'
    elsif j == 'j'
      k = 'Dagger'
    elsif j == 'k'
      k = 'Houng'
    elsif j == 'l'
      k = 'Fang'
    elsif j == 'm'
      k = 'Claw'
    elsif j == 'n'
      k = 'Wolf'
    elsif j == 'o'
      k = 'Crescent'
    elsif j == 'p'
      k = 'Paw'
    elsif j == 'q'
      k = 'Lupus'
    elsif j == 'r'
      k = 'Fire'
    elsif j == 's'
      k = 'Temptress'
    elsif j == 't'
      k = 'Warrior'
    elsif j == 'u'
      k = 'Rage'
    elsif j == 'v'
      k = 'Thorn'
    elsif j == 'w'
      k = 'Moon'
    elsif j == 'x'
      k = 'Lupe'
    elsif j == 'y'
      k = 'Vixen'
    elsif j == 'z'
      k = 'Omega'
    else
      k = j
    end
    @last = k
  end

  def dog
    @first = params[:first_name].downcase
    @last = params[:last_name].downcase
    i = @first
    j = @last
    if params[:gender] == '1' #if male
      if i == 'a'
        k = 'arnold'
      elsif i == 'b'
        k = 'wallace'
      elsif i == 'c'
        k = 'lewis'
      elsif i == 'd'
        k = 'reginald'
      elsif i == 'e'
        k = 'charlie'
      elsif i == 'f'
        k = 'burt'
      elsif i == 'g'
        k = 'ned'
      elsif i == 'h'
        k = 'clarence'
      elsif i == 'i'
        k = 'dick'
      elsif i == 'j'
        k = 'von'
      elsif i == 'k'
        k = 'stanley'
      elsif i == 'l'
        k = 'francis'
      elsif i == 'm'
        k = 'lawrence'
      elsif i == 'n'
        k = 'arthur'
      elsif i == 'o'
        k = 'fred'
      elsif i == 'p'
        k = 'gus'
      elsif i == 'q'
        k = 'tommy'
      elsif i == 'r'
        k = 'klaus'
      elsif i == 's'
        k = 'horace'
      elsif i == 't'
        k = 'buddy'
      elsif i == 'u'
        k = 'ollie'
      elsif i == 'v'
        k = 'gene'
      elsif i == 'w'
        k = 'doc'
      elsif i == 'x'
        k = 'douglas'
      elsif i == 'y'
        k = 'baxter'
      elsif i == 'z'
        k = 'mack'
      else
        k = i
      end
      @first = k
    else            # if female
      if i == 'a'
        k = 'dee'
      elsif i == 'b'
        k = 'mariel'
      elsif i == 'c'
        k = 'lois'
      elsif i == 'd'
        k = 'trudy'
      elsif i == 'e'
        k = 'jan'
      elsif i == 'f'
        k = 'gertie'
      elsif i == 'g'
        k = 'leigh'
      elsif i == 'h'
        k = 'kit'
      elsif i == 'i'
        k = 'frannie'
      elsif i == 'j'
        k = 'verla'
      elsif i == 'k'
        k = 'millie'
      elsif i == 'l'
        k = 'fay'
      elsif i == 'm'
        k = 'belva'
      elsif i == 'n'
        k = 'tammy'
      elsif i == 'o'
        k = 'merle'
      elsif i == 'p'
        k = 'leona'
      elsif i == 'q'
        k = 'ruth'
      elsif i == 'r'
        k = 'judith'
      elsif i == 's'
        k = 'ethel'
      elsif i == 't'
        k = 'lena'
      elsif i == 'u'
        k = 'moira'
      elsif i == 'v'
        k = 'jo'
      elsif i == 'w'
        k = 'june'
      elsif i == 'x'
        k = 'harriet'
      elsif i == 'y'
        k = 'gracie'
      elsif i == 'z'
        k = 'venna'
      else
        k = i
      end
      @first = k
    end
    if j == 'a'     #last name
      k = 'Howell'
    elsif j == 'b'
      k = 'McGillicuddy'
    elsif j == 'c'
      k = 'Mertz'
    elsif j == 'd'
      k = 'Petrie'
    elsif j == 'e'
      k = 'Rogers'
    elsif j == 'f'
      k = 'Sullivan'
    elsif j == 'g'
      k = 'Burr'
    elsif j == 'h'
      k = 'Wynn'
    elsif j == 'i'
      k = 'Fine'
    elsif j == 'j'
      k = 'Cunningham'
    elsif j == 'k'
      k = 'Cleaver'
    elsif j == 'l'
      k = 'Clark'
    elsif j == 'm'
      k = 'Hitchcock'
    elsif j == 'n'
      k = 'Cabot'
    elsif j == 'o'
      k = 'Howard'
    elsif j == 'p'
      k = 'Waring'
    elsif j == 'q'
      k = 'Berle'
    elsif j == 'r'
      k = 'Como'
    elsif j == 's'
      k = 'Karloff'
    elsif j == 't'
      k = 'Klugman'
    elsif j == 'u'
      k = 'Crockett'
    elsif j == 'v'
      k = 'Winkler'
    elsif j == 'w'
      k = 'King'
    elsif j == 'x'
      k = 'Lear'
    elsif j == 'y'
      k = "O'connor"
    elsif j == 'z'
      k = 'Ricardo'
    else
      k = j
    end
    @last = k
  end

  def gangster
    @first = params[:first_name].downcase
    @text = ""
    @first.split("").each do |i|
      if i == 'a'
        k = 'sha'
      elsif i == 'b'
        k = 'ni'
      elsif i == 'c'
        k = 'ki'
      elsif i == 'd'
        k = 'que'
      elsif i == 'e'
        k = 'nay'
      elsif i == 'f'
        k = 'qui'
      elsif i == 'g'
        k = 'ti'
      elsif i == 'h'
        k = 'la'
      elsif i == 'i'
        k = 'kay'
      elsif i == 'j'
        k = 'ri'
      elsif i == 'k'
        k = 'barack'
      elsif i == 'l'
        k = 'obama'
      elsif i == 'm'
        k = 'di'
      elsif i == 'n'
        k = 'ta'
      elsif i == 'o'
        k = 'ee'
      elsif i == 'p'
        k = 'ray'
      elsif i == 'q'
        k = 'cli'
      elsif i == 'r'
        k = 'gurl'
      elsif i == 's'
        k = 'na'
      elsif i == 't'
        k = 'qua'
      elsif i == 'u'
        k = 'kwa'
      elsif i == 'v'
        k = 'ise'
      elsif i == 'w'
        k = 'fi'
      elsif i == 'x'
        k = 'quee'
      elsif i == 'y'
        k = 'mi'
      elsif i == 'z'
        k = 'si'
      else
        k = i
      end
      @text += k
    end
  end

  def ninja
    @first = params[:first_name].downcase
    @text = ""
    @first.split("").each do |i|
      if i == 'a'
        k = 'ka'
      elsif i == 'b'
        k = 'zu'
      elsif i == 'c'
        k = 'mi'
      elsif i == 'd'
        k = 'te'
      elsif i == 'e'
        k = 'ku'
      elsif i == 'f'
        k = 'lu'
      elsif i == 'g'
        k = 'ji'
      elsif i == 'h'
        k = 'ri'
      elsif i == 'i'
        k = 'ki'
      elsif i == 'j'
        k = 'zu'
      elsif i == 'k'
        k = 'me'
      elsif i == 'l'
        k = 'ta'
      elsif i == 'm'
        k = 'rin'
      elsif i == 'n'
        k = 'to'
      elsif i == 'o'
        k = 'mo'
      elsif i == 'p'
        k = 'no'
      elsif i == 'q'
        k = 'ke'
      elsif i == 'r'
        k = 'shi'
      elsif i == 's'
        k = 'ari'
      elsif i == 't'
        k = 'chi'
      elsif i == 'u'
        k = 'do'
      elsif i == 'v'
        k = 'ru'
      elsif i == 'w'
        k = 'mei'
      elsif i == 'x'
        k = 'na'
      elsif i == 'y'
        k = 'fu'
      elsif i == 'z'
        k = 'zi'
      else
        k = i
      end
      @text += k
    end
  end
end
